<?php

/**
 * Implements hook_theme().
 */
function bootstrap_blocks_theme($existing, $type, $theme, $path) {
  $base = array(
    'preprocess functions' => array('bootstrap_blocks_preprocess_bblock'),
    'variables' => array('bblock_id' => null),
    'variables' => array('text_align' => null),
  );
  return array(
    'accordion' =>array(
      'variables' => array(
        'tabs_padding'       => null,
        'tabs_margin'        => null,
        'always_open' => null,
        'tabs' => array(), 
        'bblock_id' => null, 
        'text_align' => null, 
      ),
      'template' => 'templates/accordion',
    ) + $base,

    'tabs' =>array(
      'variables' => array(
        'bblock_id' => null, 
        'text_align' => null, 
        'tabs_padding'       => null,
        'tabs_margin'        => null,
        'link_style'        => null,
        'tabs'        => array(),
      ),
      'template' => 'templates/tabs',
    ) + $base,

    'tabs_vertical' =>array(
      'variables' => array(
        'bblock_id' => null, 
        'text_align' => null, 
        'tabs_padding'       => null,
        'tabs_margin'        => null,
        'tabs'        => array(),
      ),
      'template' => 'templates/tabs-vertical',
    ) + $base,

    'complete_card' =>array(
      'variables' => array(
        'card_header'      => null,
        'card_title'      => null,
        'card_title_tag'      => null,
        'card_content'    => null,
        'card_footer'    => null,
        'card_padding'    => null,
        'card_margin'     => null,
        'card_round'      => null, 
        'text_align'      => null, 
        'bblock_id' => null, 
        'text_align' => null, 
      ),
      'template' => 'templates/complete-card',
    ) + $base,

    'card_group' =>array(
      'variables' => array(
        'card_title_tag'      => null,
        'card_padding'    => null,
        'card_margin'     => null,
        'card_round'      => null, 
        'text_align'      => null, 
        'bblock_id' => null, 
        'text_align' => null, 
        'cards' => array(), 
      ),
      'template' => 'templates/card-group',
    ) + $base,

    'image_card' =>array(
      'variables' => array(
        'image'      => null,
        'image_path'      => null,
        'card_title'      => null,
        'card_title_tag'      => null,
        'card_content'    => null,
        'card_footer'    => null,
        'card_padding'    => null,
        'card_margin'     => null,
        'card_round'      => null, 
        'text_align'      => null, 
        'bblock_id' => null, 
        'text_align' => null, 
        'image_position' => null, 
      ),
      'template' => 'templates/image-card',
    ) + $base,
    
    'hero' =>array(
      'variables' => array(
        'hero_title'            => null,
        'hero_category'         => null,
        'hero_content'          => null,
        'hero_padding'          => null,
        'hero_margin'           => null,
        'hero_round'            => null, 
        'hero_button_title'     => null,
        'hero_button_url'       => null,
        'hero_background_url'   => null, 
        'hero_background_title' => null, 
        'hero_background_alt'   => null,
        'hero_card_title'       => null,
        'hero_card_content'     => null,
        'hero_card_link_title'  => null,
        'hero_card_link_url'    => null,
        'bblock_id' => null, 
        'text_align' => null, 
      ),
      'template' => 'templates/hero',
    ) + $base,
  );
}

function bootstrap_blocks_block_info() {
  $blocks['bootstrap_blocks'] = array(
    'info' => t('Bootstrap blocks'),
    'description' => t('Bootstrap blocks.'),
    'class' => 'BootstrapBlock',
    // 'required contexts' => array('node' => 'node'),
  );

  return $blocks;
}

function bootstrap_blocks_get_children() {
  $children = [
    'accordion' => [
      'info' => t('Accordion'),
      'description' => t('Accordion.'),
      'class' => 'Accordion',
      ],
    'complete_card' => [
      'info' => t('CompleteCard'),
      'description' => t('CompleteCard.'),
      'class' => 'CompleteCard',
      ],
    'hero' => [
      'info' => t('Hero'),
      'description' => t('Hero.'),
      'class' => 'Hero',
      ],
    'image_card' => [
      'info' => t('ImageCard'),
      'description' => t('ImageCard'),
      'class' => 'ImageCard',
      ],
    'tabs' => [
      'info' => t('Tabs'),
      'description' => t('Displays.'),
      'class' => 'Tabs',
      ],
    'tabs_vertical' => [
      'info' => t('TabsVertical'),
      'description' => t('Displays.'),
      'class' => 'TabsVertical',
      ],
    'card_group' => [
      'info' => t('CardGroup'),
      'description' => t('CardGroup.'),
      'class' => 'CardGroup',
      ],
  ];

  return $children;
}

/**
 * Implements hook_autoload_info().
 */
function bootstrap_blocks_autoload_info() {
  $autoload = array();
  $autoload['BootstrapBlocks'] = 'includes/BootstrapBlocks.inc';
  $autoload['BootstrapBlock'] = 'includes/BootstrapBlock.inc';
  foreach (bootstrap_blocks_get_children() as $child) {
    $autoload[$child['class']] = 'includes/' . $child['class'] . '.inc';
  }
  return $autoload;
}

/**
 * AJAX callback to update the style settings within the block configure form.
 */
function bootstrap_blocks_add_tab_ajax($form, $form_state) {
  return $form['tabs'];
}

/**
 * AJAX callback to update the style settings within the block configure form.
 */
function bootstrap_blocks_add_card_ajax($form, $form_state) {
  return $form['cards'];
}

/**
 * AJAX callback to update the style settings within the block configure form.
 */
function bootstrap_blocks_add_tab_submit($form, &$form_state) {
  $form_state['tabs'][] = ['title' => '', 'content' => ''];
  $form_state['rebuild'] = TRUE;
}

/**
 * AJAX callback to update the style settings within the block configure form.
 */
function bootstrap_blocks_add_card_submit($form, &$form_state) {
  $form_state['cards'][] = ['card_title' => '', 'card_content' => '', 'card_header' => '', 'card_footer' => ''];
  $form_state['rebuild'] = TRUE;
}

/**
 * AJAX callback to update the style settings within the block configure form.
 */
function bootstrap_blocks_preprocess_bblock(&$variables) {
  if (!empty($variables['bblock_id'])) {
    $variables['bblock_id'] = strtolower(backdrop_clean_css_identifier($variables['bblock_id']));
  }
  else {
    $variables['bblock_id'] = 'bblock-block';
  }

  if ($variables['text_align'] == 'left') {
    $variables['text_align'] = '';
  }
  elseif ($variables['text_align'] == 'right') {
    $variables['text_align'] = 'text-end';
  }
  elseif ($variables['text_align'] == 'center') {
    $variables['text_align'] = 'text-center';
  }
    
  dpm($variables);

}
